### PR TITLE
Fixing namespace collision

### PR DESCRIPTION
**Pull request by soniktrooth**
oh the Derpals

Alternative Fact Solution: https://www.drupal.org/node/2851601

### CODE REVIEW

**Comment by soniktrooth** [comment]
@thiagodemellobueno @RobLoach The tests are failing and it seems to be because of whitespace. I don't really understand how this holds together and I'm in a glass case of emotion.

**Comment by RobLoach** [comment]
This is a breaking change (requires a major release), as it will require a change across all projects using KalaStatic. Is there a cleaner way in order for us to accomplish this? Perhaps in kalastatic_dot_module?

**Comment by soniktrooth** [comment]
Sorry Rob I should have elaborated. The Components module automatically adds a namespace for each module that points to the module in the file system. Without this proposed change Kalastatic would have to live in the kalastatc Drupal module. 4.0 here we come ;)

**Comment by andrewmallis** [comment]
#403 on the 4.0 question

**Comment by RobLoach** [comment]
https://www.drupal.org/node/2851601

**Comment by RobLoach** [comment]
This is better:
https://www.drupal.org/node/2852837

**Pull request closed without merging**
