### PR TITLE
Navupdate

### PR DESCRIPTION
**Pull request by madeofpeople**
Number of files change is because this branch is built off the as yet unmerged examplesfix branch.

Its just these sets of changes: https://github.com/kalamuna/kalastatic/commit/52e38c28f5e2c07bb7d6fb41cd8f862b745e7b07

@RobLoach @andrewmallis @soniktrooth thoughts?
Can we merge it in? ... pleeeeeease. can we?

### CODE REVIEW

**Comment by madeofpeople** [comment]
Quick updates.

**Comment by soniktrooth** [comment]
This is the bizniz right here. Looking tight. Can we merge pretty please?

**Comment by andrewmallis** [comment]
build is failing, so… no merge yet.

Nav jumps when you click a link. That glitch could be said to be in line with the kalastatic homepage treatment, so not a blocker, but let us not get distracted by beauty of this.

I looks really great as a website, but in the context of our goals as a boilerplate, it takes us further away from something to prototype with, since nearly every site we build has a logo in the header of the site.

If we had in place a structure/system for template variance, it would be a different matter, but I am concerned about the project state on initial check-out.

I'm torn here because it looks significantly more presentable for the demo…

**Comment by RobLoach** [comment]
Manually deployed to http://navupdate-kalastatic.at.kalamuna.com .

**Comment by madeofpeople** [comment]
@RobLoach , how do i manually deploy updates to that feature branch ?

**Comment by madeofpeople** [comment]
@RobLoach that branch doesn't really reflect the changes at all.

**Comment by andrewmallis** [comment]
seems like 

```npm build deploy```

should deploy to this multidev environment, based on the contents of Gruntfile.js:

```
      // The default deployment target, set in package.json.
      deploy: {
        options: {
          remote: '<%= pkg.extra.deploy %>',
          branch: 'navupdate'
        }
      }
```

**Comment by andrewmallis** [comment]
home link now is missing @madeofpeople

**Comment by RobLoach** [comment]
The `branch` change was just temporary to force a local deployment.

**Comment by RobLoach** [comment]
This good to go?

**Comment by madeofpeople** [comment]
Aye

**Pull request merged**
