### PR TITLE
Adding extreme sass linting radness

### PR DESCRIPTION
**Pull request by soniktrooth**
Addresses #112

### CODE REVIEW

**Comment by thiagodemellobueno** [comment]
@soniktrooth this doesn't need corresponding changes to package.json?

**Comment by thiagodemellobueno** [comment]
So this works if you say, use atom and have a sass-lint package installed. But it doesn't do anything by itself. 

I figure we'd set up something like this https://github.com/sasstools/grunt-sass-lint

Running before the metalsmith build.

**Comment by thiagodemellobueno** [comment]
But great start!

**Comment by soniktrooth** [comment]
Ok, this works now. I fixed up two fatal errors so we at least have it building. 

We do, however, currently have 364 problems that need addressing. I'm in favour of calling this issue and making another to fix the warnings.

**Pull request merged**
