### PR TITLE
show news content tagged legit instead of test

### PR DESCRIPTION
**Pull request by andrewmallis**
:warning: don't merge – for demo only.

prismic demo with different content

### CODE REVIEW

**Comment by madeofpeople** [comment]
Maybe we should just NOT published those marked with draft? 
And everything else is published?

Thats the general model for static-site-generator blogging (from the jekyll days).

**Comment by andrewmallis** [comment]
sounds good @madeofpeople – though I could not find documentation on how to do that at https://github.com/mbanting/metalsmith-prismic –– thoughts?

**Comment by madeofpeople** [comment]
I didn't know these were prismic specific terminology, and that this was more just a metalsmith bit. Carry on!

**Comment by andrewmallis** [comment]
@RobLoach wondering why the prismic2 branch is not showing up on pantheon https://github.com/kalamuna/kalastatic/tree/prismic2 ?

**Comment by RobLoach** [comment]
> wondering why the prismic2 branch is not showing up on pantheon https://github.com/kalamuna/kalastatic/tree/prismic2 ?

Likely because this was before the automatic branch deployment... Just merged master in to do that for us.

**Comment by RobLoach** [comment]
Going to close this, we've proved it works. It's fun, educational, and sassy.

**Pull request closed without merging**
