### PR TITLE
Add demo of Prismic

### PR DESCRIPTION
**Pull request by RobLoach**
:warning: Do not merge

Demo of using Prismic as a content provider.

### CODE REVIEW

**Comment by andrewmallis** [comment]
yes, let's multidev @RobLoach 
https://dashboard.getpantheon.com/sites/99097056-c6bd-451e-a94b-fc8f7666fbe5#multidev/overview/git-branches

**Comment by RobLoach** [comment]
http://prismic-kalastatic.at.kalamuna.com/news/

**Comment by andrewmallis** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by andrewmallis** [comment]
we leave this alone to get our multidev that demos prismic

**Pull request closed without merging**
