### PR TITLE
examples restructuring

### PR DESCRIPTION
**Pull request by madeofpeople**
Maybe not for now, but this stuff works, and simplifies.

@soniktrooth @RobLoach @andrewmallis

### CODE REVIEW

**Comment by soniktrooth** [comment]
This is great, makes so much more sense... clicked through and everything's fine @andrewmallis shall we? It's gold :D

**Comment by madeofpeople** [comment]
++

**Comment by RobLoach** [comment]
Looks pretty good... See any regressions? I've been clicking around.

**Comment by andrewmallis** [comment]
generally good.
regression here: http://localhost:8000/news/
but you'd have to know that URL is there. Where's that coming from. Seeing a search bar. wacky!

**Pull request merged**
